export interface Skill {
  name: string;
  category: 'frontend' | 'backend' | 'language' | 'devops' | 'database';
}

export interface ExperienceEntry {
  company: string;
  role: string;
  period: string;
  location: string;
  bullets: string[];
}

export interface HobbyEntry {
  label: string;
  icon: string;
}

export interface KitItem {
  label: string;
  value: string;
}

export interface ProjectLink {
  label: string;
  url: string;
}

export interface ProjectEntry {
  title: string;
  description: string;
  highlights: string[];
  stack: string[];
  liveUrl?: string;
  githubUrl?: string;
  links?: ProjectLink[];
}

export interface SiteContent {
  person: {
    name: string;
    title: string;
    email: string;
    linkedin: string;
    github: string;
  };
  kit: KitItem[];
  skills: Skill[];
  experience: ExperienceEntry[];
  hobbies: HobbyEntry[];
  hostingNote: string;
  projects: ProjectEntry[];
}

/**
 * ISO date (YYYY-MM-DD) of the last meaningful change to {@link siteContent}.
 *
 * The sitemap's `lastModified` derives from this (see `app/sitemap.ts`), so the
 * value must be a static, deterministic date literal — never a runtime clock or
 * git metadata — to keep the generated sitemap stable across Docker builds.
 *
 * Bump this whenever you edit `siteContent`. The `content freshness` policy test
 * (`src/data/__tests__/content.test.ts`) recomputes {@link CONTENT_FINGERPRINT}
 * and fails on mismatch, forcing content edits and this date to move together.
 * See web/CLAUDE.md → "Editing site content".
 */
export const CONTENT_LAST_UPDATED = '2026-07-28';

/**
 * SHA-256 (hex) fingerprint of {@link siteContent} as of
 * {@link CONTENT_LAST_UPDATED}. Regenerated by the `content freshness` test's
 * failure message whenever content changes — copy the reported hash here and
 * bump {@link CONTENT_LAST_UPDATED} in the same commit.
 */
export const CONTENT_FINGERPRINT =
  '3d03fc39767caf794efb78b84202ddb21638e67e119fe893ec3b64c5ab85d7f7';

export const siteContent: SiteContent = {
  person: {
    name: 'Justin Sawyer',
    title: 'Software Engineer | Ergo Keyboard Enthusiast',
    email: 'justin@jussaw.com',
    github: 'https://github.com/jussaw',
    linkedin: 'https://linkedin.com/in/jussaw',
  },
  kit: [
    { label: 'keyboard', value: 'Corne LP w/ nice!nano' },
    { label: 'laptop', value: 'M2 MacBook Air' },
    { label: 'headphones', value: 'AirPods Pro 3' },
    { label: 'browser', value: 'Zen Browser' },
    { label: 'editor', value: 'VS Code' },
    { label: 'terminal', value: 'iTerm2' },
  ],
  skills: [
    { name: 'React', category: 'frontend' },
    { name: 'Next.js', category: 'frontend' },
    { name: 'Angular', category: 'frontend' },
    { name: 'Tailwind CSS', category: 'frontend' },
    { name: 'TypeScript', category: 'language' },
    { name: 'JavaScript', category: 'language' },
    { name: 'Java', category: 'language' },
    { name: 'Python', category: 'language' },
    { name: 'Node.js', category: 'backend' },
    { name: 'Spring Boot', category: 'backend' },
    { name: 'REST / OpenAPI', category: 'backend' },
    { name: 'PostgreSQL', category: 'database' },
    { name: 'MySQL', category: 'database' },
    { name: 'Redis', category: 'database' },
    { name: 'MongoDB', category: 'database' },
    { name: 'Docker', category: 'devops' },
    { name: 'AWS', category: 'devops' },
    { name: 'GitHub Actions', category: 'devops' },
  ],
  experience: [
    {
      company: 'Cargill',
      role: 'Tech Lead',
      period: '2025 - Present',
      location: 'Atlanta, GA',
      bullets: [
        'Technical lead for the application formulators at ground meat plants across North America use to build, cost, and manage product formulations — own architecture, technical direction, and team process while continuing to ship features hands-on.',
        "Engineering owner of the solver's production behavior — triaging infeasibilities and constraint errors, shipping LP model and penalty-lever changes in partnership with the team's data scientist, and giving formulators tunable control over cost versus inventory position. Built solve traceability (input fingerprinting, MIP-gap capture, archived solver I/O) that cut time-to-diagnose from hours to minutes.",
        "Cut payload on the application's most-used data view by 90% (15.5 MB → 1.9 MB) and load time from 6.3s to 0.67s; drove a modernization slate to production spanning backend framework and runtime upgrades, frontend build tooling and package manager migration, and decomposition of a monolithic API client into per-controller modules.",
        'Delivered formulator- and business-facing features end-to-end: a self-service price-forecasting screen for margin planning, a production-planning detail view with constraint and allowable-material editing, plant-configurable solver and business-rule settings that eliminated a deploy cycle per plant, and an analytics dashboard built from requirements sessions I ran directly with stakeholders.',
        'Built and shipped an internal Claude Code plugin marketplace — slash commands codifying story grooming, adversarial PR review, and the release runbook — adopted by every engineer on the team. Also prototyped a read-only MCP server exposing application data to AI assistants behind a default-deny allowlist.',
      ],
    },
    {
      company: 'Raytheon',
      role: 'Software Engineer II',
      period: '2023 - 2025',
      location: 'Denver, CO',
      bullets: [
        'Engineered a full-stack time tracking application using React and Spring Boot within a microservices architecture',
        'Designed and implemented an internal voting system with RESTful APIs and a PostgreSQL backend',
        'Partnered with the Scrum Master to facilitate sprint ceremonies and author user stories',
      ],
    },
    {
      company: 'Benchmark Analytics',
      role: 'Full Stack Developer',
      period: '2022 - 2023',
      location: 'Remote',
      bullets: [
        'Partnered with the L3/Base Application team to identify and resolve root-cause defects, reducing ticket intake by 25%',
        'Triaged and routed incoming issues during daily Agile stand-ups, directing tickets to the appropriate engineering departments',
        'Sustained consistent delivery of bug fixes across the codebase while managing a high-volume ticket backlog',
      ],
    },
    {
      company: 'T-Mobile',
      role: 'Software Engineer',
      period: '2021 - 2022',
      location: 'Remote',
      bullets: [
        "Developed scalable microservices supporting T-Mobile's device and accessory supply chain within a distributed Agile team",
        'Defined backend service contracts using Java Spring and Swagger API specifications within a BDD Agile environment',
        'Built a new Angular feature page enabling business teams to search and update SKU-level store data for the BOPIS sales model',
      ],
    },
    {
      company: 'KNAPP',
      role: 'Software Systems Engineer',
      period: '2019 - 2020',
      location: 'Atlanta, GA',
      bullets: [
        'Developed software solutions for automated warehouse systems using Python, Java, and PL/SQL in a Linux environment',
        'Deployed and configured systems on-site at facilities worldwide, spanning the United States, Canada, South America, and Europe',
        'Partnered directly with clients to customize and optimize software to their unique operational requirements',
      ],
    },
  ],
  hobbies: [
    { label: 'Ergonomic Keyboards', icon: 'FaKeyboard' },
    { label: 'Home Lab', icon: 'FaServer' },
    { label: 'Gaming', icon: 'FaGamepad' },
    { label: 'Hiking', icon: 'FaHiking' },
    { label: 'Snowboarding', icon: 'FaMountain' },
  ],
  hostingNote: 'Hosted with ❤️ on my Raspberry Pi',
  projects: [
    {
      title: 'jussaw.com',
      description: 'This site — designed, built, and self-hosted',
      highlights: [
        'Self-hosted on Raspberry Pi via Docker + Docker Compose',
        'Standalone Next.js build optimized for minimal production artifact',
        'Scroll-triggered animations with Intersection Observer API',
        'Full test coverage with Vitest + React Testing Library',
      ],
      stack: ['Next.js 16', 'TypeScript', 'Tailwind CSS 4', 'Docker', 'Raspberry Pi'],
      liveUrl: 'https://jussaw.com',
      githubUrl: 'https://github.com/jussaw/jussaw-app',
    },
    {
      title: 'HarborStats',
      description: 'Catan results tracker for a friend group',
      highlights: [
        'Doubles as an automated-development playground for my Hermes agent',
        'Full-stack app with Next.js 16 App Router, React 19, and TypeScript',
        'PostgreSQL 18 with Drizzle ORM for typed schema and migrations',
        'Password-protected admin panel for game and player data management',
        'Unit, component, integration, and end-to-end tests with Vitest + Playwright',
        'Self-hosted on Raspberry Pi via Docker Compose',
      ],
      stack: ['Next.js 16', 'React 19', 'TypeScript', 'PostgreSQL', 'Drizzle ORM', 'Docker'],
      liveUrl: 'https://harborstats.jussaw.com',
      githubUrl: 'https://github.com/jussaw/harborstats',
    },
    {
      title: 'FullHex',
      description: 'Browser extension for edge-to-edge colonist.io',
      highlights: [
        'Manifest V3 extension for Chrome, Edge, Brave, and Firefox',
        'Removes the blank 165px side and 90px bottom ad-space gutters so the board fills the window',
        'Triggers the colonist.io native fill-the-window layout by overriding document.fullscreenElement',
        'Zero dependencies — vanilla JS + CSS, no tracking, accounts, or configuration',
      ],
      stack: ['JavaScript', 'CSS', 'Manifest V3', 'Browser Extension'],
      links: [
        {
          label: 'Chrome Web Store',
          url: 'https://chromewebstore.google.com/detail/fullhex/kaiekkbjpleiknlcldekffadmobdeahd',
        },
        { label: 'Firefox Add-on', url: 'https://addons.mozilla.org/en-US/firefox/addon/fullhex/' },
        { label: 'GitHub', url: 'https://github.com/jussaw/fullhex' },
        { label: 'Privacy Policy', url: 'https://fullhex.jussaw.com/' },
      ],
    },
    {
      title: 'zmk-config',
      description: 'ZMK wireless firmware config for my wireless keyboards',
      highlights: [
        'Keyboard-agnostic repo — one keymap/conf pair and CI build target per board',
        'Colemak-DH base with home row mods (A/R/S/T and N/E/I/O) across 6 layers',
        'Bluetooth multi-device profiles, a mouse/pointer layer, Hyper key, and SOCD cleaning for gaming',
        'GitHub Actions builds a .uf2 for every board, with ZMK Studio support on the Corne',
      ],
      stack: ['ZMK Firmware', 'Devicetree', 'GitHub Actions'],
      githubUrl: 'https://github.com/jussaw/zmk-config',
    },
    {
      title: 'qmk-userspace',
      description: 'External QMK keymaps for several wired keyboards',
      highlights: [
        'Keymaps for the Corne, Charybdis 3x6, Planck, and Ploopy trackball',
        'Corne runs Colemak-DHm with home row mods (A/R/S/T and N/E/I/O)',
        'Charybdis trackball with DPI, sniping, and drag-scroll controls',
        'GitHub Actions builds firmware without forking upstream QMK',
      ],
      stack: ['QMK Firmware', 'C', 'GitHub Actions'],
      githubUrl: 'https://github.com/jussaw/qmk-userspace',
    },
  ],
};
